default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # username: <%= ENV['USERNAME'] %>
  # password: <%= ENV['PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: pick_another_dev
  # adapter: <%= ENV["DB_ADAPTER"] || "sqlite3" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  # Important configs for cloud9, change password value
  # to what you entered in the previous psql step.
  # template: template0
  # username: username
  # password: password
  template: template1
  username: postgres
  password: password

test:
  <<: *default
  database: pick_another_test

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
